source('./R/process_BSM_events.R')
#path is the relative path to immigration results (e.g. ./output/mammals/immigration/,./output/birds/immigration/)
generate_dispersal_speciation_averageplots<-function(pathmammals,pathbirds,name){
  cat('getting rates and events for mammals','\n')
  results.BSM.real.afrotrop.mammals<-readRDS(paste(pathmammals,'/','/whole_realms/afrotrop/afrotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.afrotrop.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.afrotrop.mammals[[2]],name='afrotrop',speciation.rate.treefile='./output/mammals/trees/afrotrop_speciationrates.tree')
  results.BSM.real.austral.mammals<-readRDS(paste(pathmammals,'/','whole_realms/austral/austral.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.austral.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.austral.mammals[[2]],name='austral',speciation.rate.treefile='./output/mammals/trees/austral_speciationrates.tree')
  results.BSM.real.indo.mammals<-readRDS(paste(pathmammals,'/','whole_realms/indo/indo.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.indo.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.indo.mammals[[2]],name='indo',speciation.rate.treefile='./output/mammals/trees/indo_speciationrates.tree')
  results.BSM.real.nearctic.mammals<-readRDS(paste(pathmammals,'/','whole_realms/nearctic/nearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.nearctic.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.nearctic.mammals[[2]],name='nearctic',speciation.rate.treefile='./output/mammals/trees/nearctic_speciationrates.tree')
  results.BSM.real.neotrop.mammals<-readRDS(paste(pathmammals,'/','whole_realms/neotrop/neotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.neotrop.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.neotrop.mammals[[2]],name='neotrop',speciation.rate.treefile='./output/mammals/trees/neotrop_speciationrates.tree')
  results.BSM.real.palearctic.mammals<-readRDS(paste(pathmammals,'/','whole_realms/palearctic/palearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.palearctic.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.palearctic.mammals[[2]],name='palearctic',speciation.rate.treefile='./output/mammals/trees/palearctic_speciationrates.tree')
  
  cat('getting rates and events for birds','\n')
  results.BSM.real.afrotrop.birds<-readRDS(paste(pathbirds,'/','/whole_realms/afrotrop/afrotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.afrotrop.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.afrotrop.birds[[2]],name='afrotrop',speciation.rate.treefile='./output/birds/trees/afrotrop_speciationrates.tree')
  results.BSM.real.austral.birds<-readRDS(paste(pathbirds,'/','whole_realms/austral/austral.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.austral.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.austral.birds[[2]],name='austral',speciation.rate.treefile='./output/birds/trees/austral_speciationrates.tree')
  results.BSM.real.indo.birds<-readRDS(paste(pathbirds,'/','whole_realms/indo/indo.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.indo.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.indo.birds[[2]],name='indo',speciation.rate.treefile='./output/birds/trees/indo_speciationrates.tree')
  results.BSM.real.nearctic.birds<-readRDS(paste(pathbirds,'/','whole_realms/nearctic/nearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.nearctic.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.nearctic.birds[[2]],name='nearctic',speciation.rate.treefile='./output/birds/trees/nearctic_speciationrates.tree')
  results.BSM.real.neotrop.birds<-readRDS(paste(pathbirds,'/','whole_realms/neotrop/neotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.neotrop.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.neotrop.birds[[2]],name='neotrop',speciation.rate.treefile='./output/birds/trees/neotrop_speciationrates.tree')
  results.BSM.real.palearctic.birds<-readRDS(paste(pathbirds,'/','whole_realms/palearctic/palearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.palearctic.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.palearctic.birds[[2]],name='palearctic',speciation.rate.treefile='./output/birds/trees/palearctic_speciationrates.tree')
  
  cat('generating average dispersal plots','\n')
  afro.dispersal<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.afrotrop.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.afrotrop.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.afrotrop.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.afrotrop.real.birds.2my[[2]],age=26,name='afrotrop',plots='within.realm.dispersal.rates',ylim=6)
  austral.dispersal<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.austral.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.austral.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.austral.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.austral.real.birds.2my[[2]],age=26,name='austral',plots='within.realm.dispersal.rates',ylim=6)
  indo.dispersal<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.indo.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.indo.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.indo.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.indo.real.birds.2my[[2]],age=26,name='indo',plots='within.realm.dispersal.rates',ylim=6)
  nearctic.dispersal<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.nearctic.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.nearctic.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.nearctic.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.nearctic.real.birds.2my[[2]],age=26,name='nearctic',plots='within.realm.dispersal.rates',ylim=6)
  neotrop.dispersal<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.neotrop.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.neotrop.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.neotrop.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.neotrop.real.birds.2my[[2]],age=26,name='neotrop',plots='within.realm.dispersal.rates',ylim=6)
  palearctic.dispersal<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.palearctic.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.palearctic.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.palearctic.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.palearctic.real.birds.2my[[2]],age=26,name='palearctic',plots='within.realm.dispersal.rates',ylim=6)
  
  afro.dispersal<-lapply(afro.dispersal,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  austral.dispersal<-lapply(austral.dispersal,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  indo.dispersal<-lapply(indo.dispersal,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  nearctic.dispersal<-lapply(nearctic.dispersal,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  neotrop.dispersal<-lapply(neotrop.dispersal,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  palearctic.dispersal<-lapply(palearctic.dispersal,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  
  pdf(paste('./output/mammals/plots/Fig3_dispersal_',name,'.pdf',sep=''),width=10,height=7)
  matrix.bxp<-t(do.call('rbind',c(afro.dispersal,0,austral.dispersal,0,indo.dispersal,0,neotrop.dispersal,0,nearctic.dispersal,0,palearctic.dispersal)))
  max.bxp<-max(abs(matrix.bxp))
  bxp(list(stats=matrix.bxp,n=rep(10,17)),boxfill=c(rep(c('#009999',"#FF7400",0),times=6)),xaxt='n',ylim=c(-max.bxp,max.bxp),main='dispersal rates H-N minus N-H')
  axis(1,at=seq(from=1.5,to=16.5,by=3),labels=c('Afro','Austral','Indo','Neotrop','Nearctic','Palearctic'))
  abline(h=0,lty=5)
  abline(v=seq(from=3,to=15,by=3),lty=3)
  dev.off()
  
  
  cat('generating average speciation plots','\n')
  afro.speciation<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.afrotrop.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.afrotrop.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.afrotrop.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.afrotrop.real.birds.2my[[2]],age=26,name='afrotrop',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  austral.speciation<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.austral.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.austral.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.austral.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.austral.real.birds.2my[[2]],age=26,name='austral',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  indo.speciation<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.indo.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.indo.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.indo.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.indo.real.birds.2my[[2]],age=26,name='indo',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  nearctic.speciation<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.nearctic.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.nearctic.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.nearctic.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.nearctic.real.birds.2my[[2]],age=26,name='nearctic',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  neotrop.speciation<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.neotrop.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.neotrop.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.neotrop.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.neotrop.real.birds.2my[[2]],age=26,name='neotrop',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  palearctic.speciation<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.palearctic.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.palearctic.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.palearctic.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.palearctic.real.birds.2my[[2]],age=26,name='palearctic',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  
  
  afro.speciation<-lapply(afro.speciation,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  austral.speciation<-lapply(austral.speciation,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  indo.speciation<-lapply(indo.speciation,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  nearctic.speciation<-lapply(nearctic.speciation,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  neotrop.speciation<-lapply(neotrop.speciation,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  palearctic.speciation<-lapply(palearctic.speciation,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  
  pdf(paste('./output/mammals/plots/Fig2_speciation_',name,'.pdf',sep=''),width=10,height=7)
  matrix.bxp<-t(do.call('rbind',c(afro.speciation,0,austral.speciation,0,indo.speciation,0,neotrop.speciation,0,nearctic.speciation,0,palearctic.speciation)))
  max.bxp<-max(abs(matrix.bxp))
  bxp(list(stats=matrix.bxp,n=rep(10,17)),boxfill=c(rep(c('#009999',"#FF7400",0),times=6)),xaxt='n',ylim=c(-max.bxp,max.bxp))
  axis(1,at=seq(from=1.5,to=16.5,by=3),labels=c('Afro','Austral','Indo','Neotrop','Nearctic','Palearctic'))
  abline(h=0,lty=5)
  abline(v=seq(from=3,to=15,by=3),lty=3)
  dev.off()
  
}

generate_dispersal_speciation_throughtimeplots<-function(pathmammals,pathbirds,name){
  cat('getting rates and events for mammals','\n')
  results.BSM.real.afrotrop.mammals<-readRDS(paste(pathmammals,'/','/whole_realms/afrotrop/afrotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.afrotrop.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.afrotrop.mammals[[2]],name='afrotrop',speciation.rate.treefile='./output/mammals/trees/afrotrop_speciationrates.tree')
  results.BSM.real.austral.mammals<-readRDS(paste(pathmammals,'/','whole_realms/austral/austral.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.austral.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.austral.mammals[[2]],name='austral',speciation.rate.treefile='./output/mammals/trees/austral_speciationrates.tree')
  results.BSM.real.indo.mammals<-readRDS(paste(pathmammals,'/','whole_realms/indo/indo.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.indo.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.indo.mammals[[2]],name='indo',speciation.rate.treefile='./output/mammals/trees/indo_speciationrates.tree')
  results.BSM.real.nearctic.mammals<-readRDS(paste(pathmammals,'/','whole_realms/nearctic/nearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.nearctic.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.nearctic.mammals[[2]],name='nearctic',speciation.rate.treefile='./output/mammals/trees/nearctic_speciationrates.tree')
  results.BSM.real.neotrop.mammals<-readRDS(paste(pathmammals,'/','whole_realms/neotrop/neotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.neotrop.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.neotrop.mammals[[2]],name='neotrop',speciation.rate.treefile='./output/mammals/trees/neotrop_speciationrates.tree')
  results.BSM.real.palearctic.mammals<-readRDS(paste(pathmammals,'/','whole_realms/palearctic/palearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.palearctic.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.palearctic.mammals[[2]],name='palearctic',speciation.rate.treefile='./output/mammals/trees/palearctic_speciationrates.tree')
  
  cat('getting rates and events for birds','\n')
  results.BSM.real.afrotrop.birds<-readRDS(paste(pathbirds,'/','/whole_realms/afrotrop/afrotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.afrotrop.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.afrotrop.birds[[2]],name='afrotrop',speciation.rate.treefile='./output/birds/trees/afrotrop_speciationrates.tree')
  results.BSM.real.austral.birds<-readRDS(paste(pathbirds,'/','whole_realms/austral/austral.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.austral.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.austral.birds[[2]],name='austral',speciation.rate.treefile='./output/birds/trees/austral_speciationrates.tree')
  results.BSM.real.indo.birds<-readRDS(paste(pathbirds,'/','whole_realms/indo/indo.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.indo.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.indo.birds[[2]],name='indo',speciation.rate.treefile='./output/birds/trees/indo_speciationrates.tree')
  results.BSM.real.nearctic.birds<-readRDS(paste(pathbirds,'/','whole_realms/nearctic/nearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.nearctic.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.nearctic.birds[[2]],name='nearctic',speciation.rate.treefile='./output/birds/trees/nearctic_speciationrates.tree')
  results.BSM.real.neotrop.birds<-readRDS(paste(pathbirds,'/','whole_realms/neotrop/neotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.neotrop.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.neotrop.birds[[2]],name='neotrop',speciation.rate.treefile='./output/birds/trees/neotrop_speciationrates.tree')
  results.BSM.real.palearctic.birds<-readRDS(paste(pathbirds,'/','whole_realms/palearctic/palearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.palearctic.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.palearctic.birds[[2]],name='palearctic',speciation.rate.treefile='./output/birds/trees/palearctic_speciationrates.tree')
  
  
  cat('generating dispersal through time plots','\n')
  pdf(paste('./output/mammals/plots/Fig3_dispersalthroughtime_',name,'.pdf',sep=''),width=10,height=7)
  par(mfrow=c(2,3))
  plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis(BSMoutput.real.rates.mammals=BSMoutput.afrotrop.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.afrotrop.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.afrotrop.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.afrotrop.real.birds.2my[[2]],age=26,name='afrotrop',plots='within.realm.dispersal.rates',ylim=6)
  plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis(BSMoutput.real.rates.mammals=BSMoutput.austral.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.austral.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.austral.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.austral.real.birds.2my[[2]],age=26,name='austral',plots='within.realm.dispersal.rates',ylim=6)
  plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis(BSMoutput.real.rates.mammals=BSMoutput.indo.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.indo.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.indo.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.indo.real.birds.2my[[2]],age=26,name='indo',plots='within.realm.dispersal.rates',ylim=6)
  plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis(BSMoutput.real.rates.mammals=BSMoutput.nearctic.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.nearctic.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.nearctic.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.nearctic.real.birds.2my[[2]],age=26,name='nearctic',plots='within.realm.dispersal.rates',ylim=6)
  plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis(BSMoutput.real.rates.mammals=BSMoutput.neotrop.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.neotrop.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.neotrop.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.neotrop.real.birds.2my[[2]],age=26,name='neotrop',plots='within.realm.dispersal.rates',ylim=6)
  plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis(BSMoutput.real.rates.mammals=BSMoutput.palearctic.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.palearctic.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.palearctic.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.palearctic.real.birds.2my[[2]],age=26,name='palearctic',plots='within.realm.dispersal.rates',ylim=6)
  dev.off()
  
  cat('generating speciation through time plots','\n')
  pdf(paste('./output/mammals/plots/Fig2_speciationthroughtime_',name,'.pdf',sep=''),width=10,height=7)
  par(mfrow=c(2,3))
  plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis(BSMoutput.real.rates.mammals=BSMoutput.afrotrop.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.afrotrop.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.afrotrop.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.afrotrop.real.birds.2my[[2]],age=24,name='afrotrop',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis(BSMoutput.real.rates.mammals=BSMoutput.austral.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.austral.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.austral.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.austral.real.birds.2my[[2]],age=24,name='austral',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis(BSMoutput.real.rates.mammals=BSMoutput.indo.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.indo.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.indo.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.indo.real.birds.2my[[2]],age=24,name='indo',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis(BSMoutput.real.rates.mammals=BSMoutput.nearctic.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.nearctic.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.nearctic.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.nearctic.real.birds.2my[[2]],age=24,name='nearctic',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis(BSMoutput.real.rates.mammals=BSMoutput.neotrop.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.neotrop.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.neotrop.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.neotrop.real.birds.2my[[2]],age=24,name='neotrop',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis(BSMoutput.real.rates.mammals=BSMoutput.palearctic.real.mammals.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.palearctic.real.mammals.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.palearctic.real.birds.2my[[1]],BSMoutput.real.events.birds=BSMoutput.palearctic.real.birds.2my[[2]],age=24,name='palearctic',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  dev.off()
}

generate_colonisation_times<-function(pathmammals,pathbirds,name){
  cat('getting rates and events for mammals','\n')
  results.BSM.real.afrotrop.mammals<-readRDS(paste(pathmammals,'/','/whole_realms/afrotrop/afrotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.afrotrop.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.afrotrop.mammals[[2]],name='afrotrop',speciation.rate.treefile='./output/mammals/trees/afrotrop_speciationrates.tree')
  results.BSM.real.austral.mammals<-readRDS(paste(pathmammals,'/','whole_realms/austral/austral.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.austral.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.austral.mammals[[2]],name='austral',speciation.rate.treefile='./output/mammals/trees/austral_speciationrates.tree')
  results.BSM.real.indo.mammals<-readRDS(paste(pathmammals,'/','whole_realms/indo/indo.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.indo.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.indo.mammals[[2]],name='indo',speciation.rate.treefile='./output/mammals/trees/indo_speciationrates.tree')
  results.BSM.real.nearctic.mammals<-readRDS(paste(pathmammals,'/','whole_realms/nearctic/nearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.nearctic.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.nearctic.mammals[[2]],name='nearctic',speciation.rate.treefile='./output/mammals/trees/nearctic_speciationrates.tree')
  results.BSM.real.neotrop.mammals<-readRDS(paste(pathmammals,'/','whole_realms/neotrop/neotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.neotrop.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.neotrop.mammals[[2]],name='neotrop',speciation.rate.treefile='./output/mammals/trees/neotrop_speciationrates.tree')
  results.BSM.real.palearctic.mammals<-readRDS(paste(pathmammals,'/','whole_realms/palearctic/palearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.palearctic.real.mammals.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.palearctic.mammals[[2]],name='palearctic',speciation.rate.treefile='./output/mammals/trees/palearctic_speciationrates.tree')
  
  cat('getting rates and events for birds','\n')
  results.BSM.real.afrotrop.birds<-readRDS(paste(pathbirds,'/','/whole_realms/afrotrop/afrotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.afrotrop.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.afrotrop.birds[[2]],name='afrotrop',speciation.rate.treefile='./output/birds/trees/afrotrop_speciationrates.tree')
  results.BSM.real.austral.birds<-readRDS(paste(pathbirds,'/','whole_realms/austral/austral.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.austral.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.austral.birds[[2]],name='austral',speciation.rate.treefile='./output/birds/trees/austral_speciationrates.tree')
  results.BSM.real.indo.birds<-readRDS(paste(pathbirds,'/','whole_realms/indo/indo.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.indo.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.indo.birds[[2]],name='indo',speciation.rate.treefile='./output/birds/trees/indo_speciationrates.tree')
  results.BSM.real.nearctic.birds<-readRDS(paste(pathbirds,'/','whole_realms/nearctic/nearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.nearctic.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.nearctic.birds[[2]],name='nearctic',speciation.rate.treefile='./output/birds/trees/nearctic_speciationrates.tree')
  results.BSM.real.neotrop.birds<-readRDS(paste(pathbirds,'/','whole_realms/neotrop/neotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.neotrop.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.neotrop.birds[[2]],name='neotrop',speciation.rate.treefile='./output/birds/trees/neotrop_speciationrates.tree')
  results.BSM.real.palearctic.birds<-readRDS(paste(pathbirds,'/','whole_realms/palearctic/palearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.palearctic.real.birds.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.palearctic.birds[[2]],name='palearctic',speciation.rate.treefile='./output/birds/trees/palearctic_speciationrates.tree')
  
  #this stores the first time bin where the number of lineages > 0
  ages.realm.colonisation.mammals<-list(c(unlist(lapply(BSMoutput.afrotrop.real.mammals[[3]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.austral.real.mammals[[3]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.indo.real.mammals[[3]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.nearctic.real.mammals[[3]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.neotrop.real.mammals[[3]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.palearctic.real.mammals[[3]],function(x) length(x)-which(x>0)[1]))))
  ages.hot.colonisation.mammals<-list(c(unlist(lapply(BSMoutput.afrotrop.real.mammals[[4]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.austral.real.mammals[[4]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.indo.real.mammals[[4]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.nearctic.real.mammals[[4]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.neotrop.real.mammals[[4]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.palearctic.real.mammals[[4]],function(x) length(x)-which(x>0)[1]))))
  diff.ages.hot.minus.realm.colonisation.mammals<-mapply('-',ages.hot.colonisation.mammals,ages.realm.colonisation.mammals,SIMPLIFY=FALSE)
  
  cat('printing mammal plot','\n')
  pdf(paste('./output/mammals/plots/FigS4mammals_difference_first_colonisationtimes_fixedyaxis_',name,'.pdf',sep=''))
  plot_difference_ages_colonisation_realms(diff.ages.hot.minus.realm.colonisation=diff.ages.hot.minus.realm.colonisation.mammals,name='mammals')
  dev.off()
  
  #this stores the first time bin where the number of lineages > 0
  ages.realm.colonisation.birds<-list(c(unlist(lapply(BSMoutput.afrotrop.real.birds[[3]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.austral.real.birds[[3]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.indo.real.birds[[3]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.nearctic.real.birds[[3]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.neotrop.real.birds[[3]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.palearctic.real.birds[[3]],function(x) length(x)-which(x>0)[1]))))
  ages.hot.colonisation.birds<-list(c(unlist(lapply(BSMoutput.afrotrop.real.birds[[4]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.austral.real.birds[[4]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.indo.real.birds[[4]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.nearctic.real.birds[[4]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.neotrop.real.birds[[4]],function(x) length(x)-which(x>0)[1]))),c(unlist(lapply(BSMoutput.palearctic.real.birds[[4]],function(x) length(x)-which(x>0)[1]))))
  diff.ages.hot.minus.realm.colonisation.birds<-mapply('-',ages.hot.colonisation.birds,ages.realm.colonisation.birds,SIMPLIFY=FALSE)
  
  pdf(paste('./output/birds/plots/FigS4birds_difference_first_colonisationtimes_fixedyaxis_',name,'.pdf',sep=''))
  plot_difference_ages_colonisation_realms(diff.ages.hot.minus.realm.colonisation=diff.ages.hot.minus.realm.colonisation.birds,name='birds')
  dev.off()
  
  
}

generate_dispersal_speciation_averageplots_NRhot<-function(pathmammals,pathbirds,name){
  results.BSM.real.afrotrop.mammals.narrow<-readRDS(paste(pathmammals,'/whole_realms/afrotrop/afrotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.afrotrop.real.mammals.narrow.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.afrotrop.mammals.narrow[[2]],name='afrotrop',speciation.rate.treefile='./output/mammals/trees/afrotrop_speciationrates.tree')
  results.BSM.real.austral.mammals.narrow<-readRDS(paste(pathmammals,'whole_realms/austral/austral.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.austral.real.mammals.narrow.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.austral.mammals.narrow[[2]],name='austral',speciation.rate.treefile='./output/mammals/trees/austral_speciationrates.tree')
  results.BSM.real.indo.mammals.narrow<-readRDS(paste(pathmammals,'whole_realms/indo/indo.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.indo.real.mammals.narrow.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.indo.mammals.narrow[[2]],name='indo',speciation.rate.treefile='./output/mammals/trees/indo_speciationrates.tree')
  results.BSM.real.nearctic.mammals.narrow<-readRDS(paste(pathmammals,'whole_realms/nearctic/nearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.nearctic.real.mammals.narrow.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.nearctic.mammals.narrow[[2]],name='nearctic',speciation.rate.treefile='./output/mammals/trees/nearctic_speciationrates.tree')
  results.BSM.real.neotrop.mammals.narrow<-readRDS(paste(pathmammals,'whole_realms/neotrop/neotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.neotrop.real.mammals.narrow.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.neotrop.mammals.narrow[[2]],name='neotrop',speciation.rate.treefile='./output/mammals/trees/neotrop_speciationrates.tree')
  results.BSM.real.palearctic.mammals.narrow<-readRDS(paste(pathmammals,'whole_realms/palearctic/palearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.palearctic.real.mammals.narrow.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.palearctic.mammals.narrow[[2]],name='palearctic',speciation.rate.treefile='./output/mammals/trees/palearctic_speciationrates.tree')
  
  results.BSM.real.afrotrop.birds.narrow<-readRDS(paste(pathbirds,'/whole_realms/afrotrop/afrotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.afrotrop.real.birds.narrow.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.afrotrop.birds.narrow[[2]],name='afrotrop',speciation.rate.treefile='./output/birds/trees/afrotrop_speciationrates.tree')
  results.BSM.real.austral.birds.narrow<-readRDS(paste(pathbirds,'/whole_realms/austral/austral.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.austral.real.birds.narrow.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.austral.birds.narrow[[2]],name='austral',speciation.rate.treefile='./output/birds/trees/austral_speciationrates.tree')
  results.BSM.real.indo.birds.narrow<-readRDS(paste(pathbirds,'/whole_realms/indo/indo.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.indo.real.birds.narrow.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.indo.birds.narrow[[2]],name='indo',speciation.rate.treefile='./output/birds/trees/indo_speciationrates.tree')
  results.BSM.real.nearctic.birds.narrow<-readRDS(paste(pathbirds,'/whole_realms/nearctic/nearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.nearctic.real.birds.narrow.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.nearctic.birds.narrow[[2]],name='nearctic',speciation.rate.treefile='./output/birds/trees/nearctic_speciationrates.tree')
  results.BSM.real.neotrop.birds.narrow<-readRDS(paste(pathbirds,'/whole_realms/neotrop/neotrop.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.neotrop.real.birds.narrow.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.neotrop.birds.narrow[[2]],name='neotrop',speciation.rate.treefile='./output/birds/trees/neotrop_speciationrates.tree')
  results.BSM.real.palearctic.birds.narrow<-readRDS(paste(pathbirds,'/whole_realms/palearctic/palearctic.whole_realms_7areas_inhotoutrealm_BSM.RDS',sep=''))
  BSMoutput.palearctic.real.birds.narrow.2my<-get_BSM_BAMM_fullrates_events_2my_object(results.BSM=results.BSM.real.palearctic.birds.narrow[[2]],name='palearctic',speciation.rate.treefile='./output/birds/trees/palearctic_speciationrates.tree')
  
  
  afro.dispersal.narrow<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.afrotrop.real.mammals.narrow.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.afrotrop.real.mammals.narrow.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.afrotrop.real.birds.narrow.2my[[1]],BSMoutput.real.events.birds=BSMoutput.afrotrop.real.birds.narrow.2my[[2]],age=26,name='afrotrop',plots='within.realm.dispersal.rates',ylim=6)
  austral.dispersal.narrow<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.austral.real.mammals.narrow.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.austral.real.mammals.narrow.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.austral.real.birds.narrow.2my[[1]],BSMoutput.real.events.birds=BSMoutput.austral.real.birds.narrow.2my[[2]],age=26,name='austral',plots='within.realm.dispersal.rates',ylim=6)
  indo.dispersal.narrow<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.indo.real.mammals.narrow.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.indo.real.mammals.narrow.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.indo.real.birds.narrow.2my[[1]],BSMoutput.real.events.birds=BSMoutput.indo.real.birds.narrow.2my[[2]],age=26,name='indo',plots='within.realm.dispersal.rates',ylim=6)
  nearctic.dispersal.narrow<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.nearctic.real.mammals.narrow.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.nearctic.real.mammals.narrow.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.nearctic.real.birds.narrow.2my[[1]],BSMoutput.real.events.birds=BSMoutput.nearctic.real.birds.narrow.2my[[2]],age=26,name='nearctic',plots='within.realm.dispersal.rates',ylim=6)
  neotrop.dispersal.narrow<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.neotrop.real.mammals.narrow.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.neotrop.real.mammals.narrow.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.neotrop.real.birds.narrow.2my[[1]],BSMoutput.real.events.birds=BSMoutput.neotrop.real.birds.narrow.2my[[2]],age=26,name='neotrop',plots='within.realm.dispersal.rates',ylim=6)
  palearctic.dispersal.narrow<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.palearctic.real.mammals.narrow.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.palearctic.real.mammals.narrow.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.palearctic.real.birds.narrow.2my[[1]],BSMoutput.real.events.birds=BSMoutput.palearctic.real.birds.narrow.2my[[2]],age=26,name='palearctic',plots='within.realm.dispersal.rates',ylim=6)
  
  afro.dispersal.narrow<-lapply(afro.dispersal.narrow,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  austral.dispersal.narrow<-lapply(austral.dispersal.narrow,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  indo.dispersal.narrow<-lapply(indo.dispersal.narrow,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  nearctic.dispersal.narrow<-lapply(nearctic.dispersal.narrow,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  neotrop.dispersal.narrow<-lapply(neotrop.dispersal.narrow,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  palearctic.dispersal.narrow<-lapply(palearctic.dispersal.narrow,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  
  pdf(paste('./output/mammals/plots/narrowhotspots_Fig3_dispersal_',name,'.pdf',sep=''),width=10,height=7)
  matrix.bxp<-t(do.call('rbind',c(afro.dispersal.narrow,0,austral.dispersal.narrow,0,indo.dispersal.narrow,0,nearctic.dispersal.narrow,0,neotrop.dispersal.narrow,0,palearctic.dispersal.narrow)))
  max.bxp<-max(abs(matrix.bxp))
  bxp(list(stats=matrix.bxp,n=rep(10,17)),boxfill=c(rep(c('#009999',"#FF7400",0),times=6)),xaxt='n',ylim=c(-max.bxp,max.bxp),main='dispersal rates H-N minus N-H')
  axis(1,at=seq(from=1.5,to=16.5,by=3),labels=c('Afro','Austral','Indo','Nearctic','Neotrop','Palearctic'))
  abline(h=0,lty=5)
  abline(v=seq(from=3,to=15,by=3),lty=3)
  dev.off()
  
  
  afro.speciation.narrow<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.afrotrop.real.mammals.narrow.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.afrotrop.real.mammals.narrow.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.afrotrop.real.birds.narrow.2my[[1]],BSMoutput.real.events.birds=BSMoutput.afrotrop.real.birds.narrow.2my[[2]],age=26,name='afrotrop',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  austral.speciation.narrow<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.austral.real.mammals.narrow.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.austral.real.mammals.narrow.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.austral.real.birds.narrow.2my[[1]],BSMoutput.real.events.birds=BSMoutput.austral.real.birds.narrow.2my[[2]],age=26,name='austral',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  indo.speciation.narrow<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.indo.real.mammals.narrow.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.indo.real.mammals.narrow.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.indo.real.birds.narrow.2my[[1]],BSMoutput.real.events.birds=BSMoutput.indo.real.birds.narrow.2my[[2]],age=26,name='indo',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  nearctic.speciation.narrow<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.nearctic.real.mammals.narrow.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.nearctic.real.mammals.narrow.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.nearctic.real.birds.narrow.2my[[1]],BSMoutput.real.events.birds=BSMoutput.nearctic.real.birds.narrow.2my[[2]],age=26,name='nearctic',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  neotrop.speciation.narrow<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.neotrop.real.mammals.narrow.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.neotrop.real.mammals.narrow.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.neotrop.real.birds.narrow.2my[[1]],BSMoutput.real.events.birds=BSMoutput.neotrop.real.birds.narrow.2my[[2]],age=26,name='neotrop',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  palearctic.speciation.narrow<-plot_rates_events_real_2mybin_difference_both_scaled_fixedyaxis_average(BSMoutput.real.rates.mammals=BSMoutput.palearctic.real.mammals.narrow.2my[[1]],BSMoutput.real.events.mammals=BSMoutput.palearctic.real.mammals.narrow.2my[[2]],BSMoutput.real.rates.birds=BSMoutput.palearctic.real.birds.narrow.2my[[1]],BSMoutput.real.events.birds=BSMoutput.palearctic.real.birds.narrow.2my[[2]],age=26,name='palearctic',plots='within.realm.cladogenesis.BAMM.rates',ylim=6)
  
  afro.speciation.narrow<-lapply(afro.speciation.narrow,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  austral.speciation.narrow<-lapply(austral.speciation.narrow,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  indo.speciation.narrow<-lapply(indo.speciation.narrow,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  nearctic.speciation.narrow<-lapply(nearctic.speciation.narrow,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  neotrop.speciation.narrow<-lapply(neotrop.speciation.narrow,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  palearctic.speciation.narrow<-lapply(palearctic.speciation.narrow,function(x)c(x[1],x[1],x[2],x[3],x[3]))
  
  pdf(paste('./output/mammals/plots/narrowhotspots_Fig2_speciation_',name,'.pdf',sep=''),width=10,height=7)
  matrix.bxp<-t(do.call('rbind',c(afro.speciation.narrow,0,austral.speciation.narrow,0,indo.speciation.narrow,0,nearctic.speciation.narrow,0,neotrop.speciation.narrow,0,palearctic.speciation.narrow)))
  max.bxp<-max(abs(matrix.bxp))
  bxp(list(stats=matrix.bxp,n=rep(10,17)),boxfill=c(rep(c('#009999',"#FF7400",0),times=6)),xaxt='n',ylim=c(-max.bxp,max.bxp))
  axis(1,at=seq(from=1.5,to=16.5,by=3),labels=c('Afro','Austral','Indo','Nearctic','Neotrop','Palearctic'))
  abline(h=0,lty=5)
  abline(v=seq(from=3,to=15,by=3),lty=3)
  dev.off()
}

