library(rgdal)
library(sp)
library(rgeos)
library(maptools)
library(parallel)
library(PBSmapping)
library(cleangeo)
library(R.utils)
library(grDevices)
library(Hmisc)
library(RColorBrewer)
library(vioplot)


#predicted.table.list is a list generated by predict_sarlm_table
#world.file is the path to realm.merge.proj.RDS
#response.variable is the name of the response variable in predicted.table.list (e.g: Q1.residuals, Q4.residuals, etc)
plot_boxplots_hotspots_realms<-function(predicted.table.list,world.file,response.variable,grid.world.file,hotspot.table.file,mode){
  grid.world<-readRDS(grid.world.file)
  #get hotspot.cells
  hotspot.table<-read.table(hotspot.table.file,header=T,sep='\t')
  hotspot.cells<-hotspot.table[hotspot.table$hotspot==1,'cells']
  world<-readRDS(world.file)  
  realms.layer<-readOGR('../raw_data/GIS/Generalised_Biogeographic_Realms_2004/','brpol_fin_dd')
  #get region names
  realms.names<-unique(realms.layer@data$REALM)
  realms.names<-as.character(realms.names[realms.names!='Antarctic'])
  realms<-unique(realms.layer@data$REALM)
  cat('getting realms ready','\n')
  #drop Antarctica
  realms<-realms[realms!='Antarctic']
  #drop Oceanic
  realms<-realms[realms!='Oceanic']
  #separate by spp name
  realms.separated<-mclapply(mc.cores=ncores,realms, function(x) realms.layer[realms.layer@data$REALM==x,])
  realms.separated<-realms.separated[order(realms)]
  #merge spp polygons
  realms.separated<-mclapply(mc.cores=ncores,realms.separated, gUnaryUnion)
  #fix polygons
  realms.separated<-mclapply(mc.cores=ncores,realms.separated, function(x) gBuffer(x, width=0))
  valid<-mclapply(mc.cores=ncores,realms.separated, gIsValid)
  cat('non valid realms','\n')
  cat(length(valid[valid==F]),'\n')
  realms.separated<-lapply(realms.separated,function(x) spTransform(x, CRS(proj4string(world))))
  #drop the water bit
  cat('overlay with continents','\n')
  realms.separated.intersected<-lapply(realms.separated,function(x) gIntersection(x,world))
  #get centroids for coordinates
  realms.separated.centroids<-lapply(realms.separated,function(x) gCentroid(x))
  realms.separated.centroids[[1]]@coords[,'x']<-realms.separated.centroids[[1]]@coords[,'x']-1000
  realms.separated.centroids[[1]]@coords[,'y']<-realms.separated.centroids[[1]]@coords[,'y']-5500
  realms.separated.centroids[[2]]@coords[,'x']<-realms.separated.centroids[[2]]@coords[,'x']-1000
  realms.separated.centroids[[2]]@coords[,'y']<-realms.separated.centroids[[2]]@coords[,'y']-4000
  realms.separated.centroids[[3]]@coords[,'x']<-realms.separated.centroids[[3]]@coords[,'x']-1000
  realms.separated.centroids[[3]]@coords[,'y']<-realms.separated.centroids[[3]]@coords[,'y']-3000
  realms.separated.centroids[[4]]@coords[,'x']<-realms.separated.centroids[[4]]@coords[,'x']-4000
  realms.separated.centroids[[4]]@coords[,'y']<-realms.separated.centroids[[4]]@coords[,'y']-4000
  realms.separated.centroids[[5]]@coords[,'x']<-realms.separated.centroids[[5]]@coords[,'x']-5000
  realms.separated.centroids[[5]]@coords[,'y']<-realms.separated.centroids[[5]]@coords[,'y']-5000
  realms.separated.centroids[[6]]@coords[,'x']<-realms.separated.centroids[[6]]@coords[,'x']+12000
  realms.separated.centroids[[6]]@coords[,'y']<-realms.separated.centroids[[6]]@coords[,'y']-2500
  cat('plotting','\n')
  #plot a blue background for the sea
  #par(bg = 'aliceblue')
  #plot an empty box with the limits of the realms
  plot(c(1,1),xlim=c(min(unlist(lapply(realms.separated.intersected,function(x) bbox(x)['x',]))),max(unlist(lapply(realms.separated.intersected,function(x) bbox(x)['x',])))),ylim=c(min(unlist(lapply(realms.separated.intersected,function(x) bbox(x)['y',]))),max(unlist(lapply(realms.separated.intersected,function(x) bbox(x)['y',])))),type='n',xaxt='n',yaxt='n',xlab='',ylab='',bty='n',main=response.variable)
  #par(bg = 'white')
  #this vector contains the colours for the realms (alphabetical order)
  #colour.realms<-c('palegreen3','salmon3','turquoise4','gray87','seagreen3','khaki')
  #colour.realms<-c('gray95','gray75','gray55','gray85','gray45','gray65')
  #colour.realms<-c('palegreen3','salmon3','turquoise4','gray87','seagreen3','khaki')
  colour.realms<-sapply(brewer.pal(6,'Pastel1'),function(x)adjustcolor(x,0.3))
  
  #plot the realms
  for(i in 1:length(realms.separated.intersected)){
    plot(realms.separated.intersected[[i]],col=colour.realms[i],add=T)  
    #plot(realms.separated.intersected[[i]],col='azure3',add=T)  
  }
  #plot the hotspot cells
  lapply(hotspot.cells,function(x)plot(grid.world[[x]],col='red',add=T,lwd=0.001,border='red'))
  
  #add boxplots
  for (i in 1:length(predicted.table.list)){
    if(mode=='different'){
      subplot(fun={boxplot(value~hotspot,data=predicted.table.list[[i]][[response.variable]],notch=TRUE,boxwex=0.3,las=2,cex.axis=0.5,xaxt='n',outcext=0.01,col=rgb(1,1,1,1),outline=FALSE);stripchart(value~hotspot,data=predicted.table.list[[i]][[response.variable]], vertical = TRUE, method = "jitter", add = TRUE, pch = 20, col = c(rgb(0,0,1,0.01),rgb(1,0,0,0.01)))},x=realms.separated.centroids[[i]]@coords[,'x'],y=realms.separated.centroids[[i]]@coords[,'y'],size=c(0.7,0.7))
    }else if (mode=='same'){
      min<-min(unlist(lapply(predicted.table.list,function(x) min(x[[response.variable]][,'value']))))
      max<-max(unlist(lapply(predicted.table.list,function(x) max(x[[response.variable]][,'value']))))
      subplot(fun={boxplot(value~hotspot,data=predicted.table.list[[i]][[response.variable]],notch=TRUE,boxwex=0.3,las=2,cex.axis=0.5,xaxt='n',outcext=0.01,col=rgb(1,1,1,1),outline=FALSE,ylim=c(min,max));stripchart(value~hotspot,data=predicted.table.list[[i]][[response.variable]], vertical = TRUE, method = "jitter", add = TRUE, pch = 20, col = c(rgb(0,0,1,0.01),rgb(1,0,0,0.01)))},x=realms.separated.centroids[[i]]@coords[,'x'],y=realms.separated.centroids[[i]]@coords[,'y'],size=c(0.7,0.7))
    }
    
    #subplot(fun={density.hot<-density(predicted.table.list[[i]][[response.variable]][predicted.table.list[[i]][[response.variable]]$hotspot==1,'value']);density.non<-density(predicted.table.list[[i]][[response.variable]][predicted.table.list[[i]][[response.variable]]$hotspot==0,'value']);plot(density.hot,xlim=c(min(density.hot$x,density.non$x),max(density.hot$x,density.non$x)),ylim=c(min(density.hot$y,density.non$y),max(density.hot$y,density.non$y)),col='red',xlab='',ylab='',yaxt='n',main='');lines(density.non,col='blue')},x=realms.separated.centroids[[i]]@coords[,'x'],y=realms.separated.centroids[[i]]@coords[,'y'],size=c(0.7,0.7))
  }
  
}

plot_density_hotspots_realms<-function(predicted.table.list,world.file,response.variable,hotspot.table.file,grid.world.file,mode){
  
  grid.world<-readRDS(grid.world.file)
  #get hotspot.cells
  hotspot.table<-read.table(hotspot.table.file,header=T,sep='\t')
  hotspot.cells<-hotspot.table[hotspot.table$hotspot==1,'cells']
  world<-readRDS(world.file)  
  realms.layer<-readOGR('../raw_data/GIS/Generalised_Biogeographic_Realms_2004/','brpol_fin_dd')
  #get region names
  realms.names<-unique(realms.layer@data$REALM)
  realms.names<-as.character(realms.names[realms.names!='Antarctic'])
  realms<-unique(realms.layer@data$REALM)
  cat('getting realms ready','\n')
  #drop Antarctica
  realms<-realms[realms!='Antarctic']
  #drop Oceanic
  realms<-realms[realms!='Oceanic']
  #separate by spp name
  realms.separated<-mclapply(mc.cores=ncores,realms, function(x) realms.layer[realms.layer@data$REALM==x,])
  realms.separated<-realms.separated[order(realms)]
  #merge spp polygons
  realms.separated<-mclapply(mc.cores=ncores,realms.separated, gUnaryUnion)
  #fix polygons
  realms.separated<-mclapply(mc.cores=ncores,realms.separated, function(x) gBuffer(x, width=0))
  valid<-mclapply(mc.cores=ncores,realms.separated, gIsValid)
  cat('non valid realms','\n')
  cat(length(valid[valid==F]),'\n')
  realms.separated<-lapply(realms.separated,function(x) spTransform(x, CRS(proj4string(world))))
  #drop the water bit
  cat('overlay with continents','\n')
  realms.separated.intersected<-lapply(realms.separated,function(x) gIntersection(x,world))
  #get centroids for coordinates
  realms.separated.centroids<-lapply(realms.separated,function(x) gCentroid(x))
  realms.separated.centroids[[1]]@coords[,'x']<-realms.separated.centroids[[1]]@coords[,'x']-1000
  realms.separated.centroids[[1]]@coords[,'y']<-realms.separated.centroids[[1]]@coords[,'y']-4700
  realms.separated.centroids[[2]]@coords[,'x']<-realms.separated.centroids[[2]]@coords[,'x']-1000
  realms.separated.centroids[[2]]@coords[,'y']<-realms.separated.centroids[[2]]@coords[,'y']-3600
  realms.separated.centroids[[3]]@coords[,'x']<-realms.separated.centroids[[3]]@coords[,'x']-1000
  realms.separated.centroids[[3]]@coords[,'y']<-realms.separated.centroids[[3]]@coords[,'y']-3000
  realms.separated.centroids[[4]]@coords[,'x']<-realms.separated.centroids[[4]]@coords[,'x']-4000
  realms.separated.centroids[[4]]@coords[,'y']<-realms.separated.centroids[[4]]@coords[,'y']-4000
  realms.separated.centroids[[5]]@coords[,'x']<-realms.separated.centroids[[5]]@coords[,'x']-5000
  realms.separated.centroids[[5]]@coords[,'y']<-realms.separated.centroids[[5]]@coords[,'y']-5000
  realms.separated.centroids[[6]]@coords[,'x']<-realms.separated.centroids[[6]]@coords[,'x']+12000
  realms.separated.centroids[[6]]@coords[,'y']<-realms.separated.centroids[[6]]@coords[,'y']-2500
  
  
  cat('plotting','\n')
  #plot a blue background for the sea
  #par(bg = 'aliceblue')
  #plot an empty box with the limits of the realms
  plot(c(1,1),xlim=c(min(unlist(lapply(realms.separated.intersected,function(x) bbox(x)['x',]))),max(unlist(lapply(realms.separated.intersected,function(x) bbox(x)['x',])))),ylim=c(min(unlist(lapply(realms.separated.intersected,function(x) bbox(x)['y',]))),max(unlist(lapply(realms.separated.intersected,function(x) bbox(x)['y',])))),type='n',xaxt='n',yaxt='n',xlab='',ylab='',bty='n',main=response.variable)
  #par(bg = 'white')
  #this vector contains the colours for the realms (alphabetical order)
  #colour.realms<-c('palegreen3','salmon3','turquoise4','gray87','seagreen3','khaki')
  colour.realms<-sapply(brewer.pal(6,'Pastel1'),function(x)adjustcolor(x,0.3))
  #plot the realms
  for(i in 1:length(realms.separated.intersected)){
    plot(realms.separated.intersected[[i]],col=colour.realms[i],add=T)  
    #plot(realms.separated.intersected[[i]],col='azure3',add=T)  
  }
  #plot the hotspot cells
  lapply(hotspot.cells,function(x)plot(grid.world[[x]],col='red',add=T,lwd=0.001,border='red'))
  
  #add boxplots
  for (i in 1:length(predicted.table.list)){
    if(mode=='different'){
      subplot(fun={density.hot<-density(predicted.table.list[[i]][[response.variable]][predicted.table.list[[i]][[response.variable]]$hotspot==1,'value']);density.non<-density(predicted.table.list[[i]][[response.variable]][predicted.table.list[[i]][[response.variable]]$hotspot==0,'value']);plot(density.hot,xlim=c(min(density.hot$x,density.non$x),max(density.hot$x,density.non$x)),ylim=c(min(density.hot$y,density.non$y),max(density.hot$y,density.non$y)),col='red',xlab='',ylab='',yaxt='n',main='',yaxs='i',cex.axis=.7);polygon(density.hot, col=adjustcolor("red",0.4), border="red");abline(v=median(predicted.table.list[[i]][[response.variable]][predicted.table.list[[i]][[response.variable]]$hotspot==1,'value']),col='red');lines(density.non,col='blue');polygon(density.non, col=adjustcolor("blue",0.4), border="blue");abline(v=median(predicted.table.list[[i]][[response.variable]][predicted.table.list[[i]][[response.variable]]$hotspot==0,'value']),col='blue')},x=realms.separated.centroids[[i]]@coords[,'x'],y=realms.separated.centroids[[i]]@coords[,'y'],size=c(0.7,0.7))
    }else if (mode=='same'){
      min<-min(unlist(lapply(predicted.table.list,function(x) min(x[[response.variable]][,'value']))))
      max<-max(unlist(lapply(predicted.table.list,function(x) max(x[[response.variable]][,'value']))))
      subplot(fun={density.hot<-density(predicted.table.list[[i]][[response.variable]][predicted.table.list[[i]][[response.variable]]$hotspot==1,'value']);density.non<-density(predicted.table.list[[i]][[response.variable]][predicted.table.list[[i]][[response.variable]]$hotspot==0,'value']);plot(density.hot,xlim=c(min,max),ylim=c(min(density.hot$y,density.non$y),max(density.hot$y,density.non$y)),col='red',xlab='',ylab='',yaxt='n',yaxs='i',cex.axis=.7,main=paste('H:',round(median(predicted.table.list[[i]][[response.variable]][predicted.table.list[[i]][[response.variable]]$hotspot==1,'value']),3),' N:',round(median(predicted.table.list[[i]][[response.variable]][predicted.table.list[[i]][[response.variable]]$hotspot==0,'value']),3),sep=''),cex.main=.5);polygon(density.hot, col=adjustcolor("red",0.4), border="red");abline(v=median(predicted.table.list[[i]][[response.variable]][predicted.table.list[[i]][[response.variable]]$hotspot==1,'value']),col='red');lines(density.non,col='blue');polygon(density.non, col=adjustcolor("blue",0.4), border="blue");abline(v=median(predicted.table.list[[i]][[response.variable]][predicted.table.list[[i]][[response.variable]]$hotspot==0,'value']),col='blue')},x=realms.separated.centroids[[i]]@coords[,'x'],y=realms.separated.centroids[[i]]@coords[,'y'],size=c(0.7,0.7))
    }
    
  }
  
}


#this plots a boxplot with differences in means (with wilcox.test), it uses a list of tables produced by predict_sarlm_table, variable has to be one of the table names in table.object
plot_differences_means<-function(table.object,variable){
  wilcox.results<-list()
  for(i in 1:length(table.object)){
    table.variable.realm<-table.object[[i]][[variable]]
    wilcox<-wilcox.test(table.variable.realm[table.variable.realm$hotspot==1,'value'],table.variable.realm[table.variable.realm$hotspot==0,'value'],conf.int = T)
    wilcox.results[[i]]<-c(wilcox$conf.int[1],wilcox$conf.int[1],wilcox$estimate,wilcox$conf.int[2],wilcox$conf.int[2])
  }
  bxp(list(stats=matrix(unlist(wilcox.results),5,6),n=rep(10,length(wilcox.results))),xaxt='n',main=paste('difference Hot-NonHot ',variable,sep=''),ylab='diff in means of residuals')
  axis(1,at=c(1:length(wilcox.results)),labels=c('Afro','Austral','Indo','Nearctic','Neotrop','Palearctic'))
  abline(h=0,lty=2)
}

#this plots a boxplot with differences in means (with wilcox.test) - x axis ordered by magnitude of difference, it uses a list of tables produced by predict_sarlm_table, variable has to be one of the table names in table.object

plot_differences_means_ordered<-function(table.object,variable){
  realms<-c('Afro','Austral','Indo','Nearctic','Neotrop','Palearctic')
  wilcox.results<-list()
  for(i in 1:length(table.object)){
    table.variable.realm<-table.object[[i]][[variable]]
    wilcox<-wilcox.test(table.variable.realm[table.variable.realm$hotspot==1,'value'],table.variable.realm[table.variable.realm$hotspot==0,'value'],conf.int = T)
    wilcox.results[[i]]<-c(wilcox$conf.int[1],wilcox$conf.int[1],wilcox$estimate,wilcox$conf.int[2],wilcox$conf.int[2])
  }
  order.realms<-order(unlist(lapply(wilcox.results,function(x)x[3])))
  wilcox.results<-wilcox.results[order(unlist(lapply(wilcox.results,function(x)x[3])))]
  bxp(list(stats=matrix(unlist(wilcox.results),5,6),n=rep(10,length(wilcox.results))),xaxt='n',main=paste('difference Hot-NonHot ',variable,sep=''),ylab='diff in means of residuals')
  axis(1,at=c(1:length(wilcox.results)),labels=realms[order.realms])
  abline(h=0,lty=2)
}

plot_propdifferences_means_ordered<-function(table.object,variable){
  realms<-c('Afro','Austral','Indo','Nearctic','Neotrop','Palearctic')
  wilcox.results<-list()
  for(i in 1:length(table.object)){
    table.variable.realm<-table.object[[i]][[variable]]
    wilcox<-wilcox.test(table.variable.realm[table.variable.realm$hotspot==1,'value'],table.variable.realm[table.variable.realm$hotspot==0,'value'],conf.int = T)
    #wilcox.results[[i]]<-c(wilcox$conf.int[1],wilcox$conf.int[1],wilcox$estimate,wilcox$conf.int[2],wilcox$conf.int[2])
    wilcox.results[[i]]<-c(wilcox$conf.int[1]/abs(mean(table.variable.realm[table.variable.realm$hotspot==1,'value'])),wilcox$conf.int[1]/abs(mean(table.variable.realm[table.variable.realm$hotspot==1,'value'])),wilcox$estimate/abs(mean(table.variable.realm[table.variable.realm$hotspot==1,'value'])),wilcox$conf.int[2]/abs(mean(table.variable.realm[table.variable.realm$hotspot==1,'value'])),wilcox$conf.int[2]/abs(mean(table.variable.realm[table.variable.realm$hotspot==1,'value'])))
  }
  order.realms<-order(unlist(lapply(wilcox.results,function(x)x[3])))
  wilcox.results<-wilcox.results[order(unlist(lapply(wilcox.results,function(x)x[3])))]
  bxp(list(stats=matrix(unlist(wilcox.results),5,6),n=rep(10,length(wilcox.results))),xaxt='n',main=paste('prop difference Hot-NonHot ',variable,sep=''),ylab='diff in means of residuals')
  axis(1,at=c(1:length(wilcox.results)),labels=realms[order.realms])
  abline(h=0,lty=2)
}
#this plots a vioplot, it uses a list of tables produced by predict_sarlm_table, variable has to be one of the table names in table.object
plot_vioplots_variables<-function(table.object,variable){
  plot(1,1,ylim=c(floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value))))),xlim=c(0,7),type='n',ylab='',las=1,xlab='',xaxt='n',yaxt='n',pch=16,cex=.7,lwd=0.5,main=variable)
  for(i in 1:length(table.object)){
    table.variable.realm<-table.object[[i]][[variable]]
    vioplot(table.variable.realm[table.variable.realm$hotspot==1,'value'],col=adjustcolor( "red", alpha.f = 0.2),at=i,add=T,rectCol = adjustcolor( "red", alpha.f = 0.5),lwd=0.001,colMed = adjustcolor( "red", alpha.f = 0.9),pchMed=19)
    vioplot(table.variable.realm[table.variable.realm$hotspot==0,'value'],col=adjustcolor( "blue", alpha.f = 0.2),at=i,add=T,rectCol = adjustcolor( "blue", alpha.f = 0.5),lwd=0.001,colMed = adjustcolor( "blue", alpha.f = 0.9),pchMed=19)
  }
  axis(1,at=c(1:length(wilcox.results)),labels=c('Afro','Austral','Indo','Nearctic','Neotrop','Palearctic'),cex.axis=.7)
  axis(2,at=seq(from=floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),to=ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),by=1),labels=seq(from=floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),to=ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),by=1),las=2,cex.axis=.7)
  
}
#combine graphics
plot_propdifferencesmeans_plus_vioplots<-function(table.object,variable){
  realms<-c('Afro','Austral','Indo','Nearctic','Neotrop','Palearctic')
  wilcox.results<-list()
  for(i in 1:length(table.object)){
    table.variable.realm<-table.object[[i]][[variable]]
    wilcox<-wilcox.test(table.variable.realm[table.variable.realm$hotspot==1,'value'],table.variable.realm[table.variable.realm$hotspot==0,'value'],conf.int = T)
    wilcox.results[[i]]<-c(wilcox$conf.int[1],wilcox$conf.int[1],wilcox$estimate,wilcox$conf.int[2],wilcox$conf.int[2])
  }
  
  order.realms<-order(unlist(lapply(wilcox.results,function(x)x[3])))
  plot(1,1,ylim=c(floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value))))),xlim=c(0,7),type='n',ylab='',las=1,xlab='',xaxt='n',yaxt='n',pch=16,lwd=0.5,main=variable)
  for(i in 1:length(order.realms)){
    table.variable.realm<-table.object[[order.realms[i]]][[variable]]
    vioplot(table.variable.realm[table.variable.realm$hotspot==1,'value'],col=adjustcolor( "red", alpha.f = 0.2),border=adjustcolor( "red", alpha.f = 0.2),at=i,add=T,rectCol = adjustcolor( "red", alpha.f = 0.5),lwd=0.001,colMed = adjustcolor( "red", alpha.f = 0.9),pchMed=19)
    vioplot(table.variable.realm[table.variable.realm$hotspot==0,'value'],col=adjustcolor( "blue", alpha.f = 0.2),border=adjustcolor( "blue", alpha.f = 0.2),at=i,add=T,rectCol = adjustcolor( "blue", alpha.f = 0.5),lwd=0.001,colMed = adjustcolor( "blue", alpha.f = 0.9),pchMed=19)
  }
  axis(1,at=c(1:length(wilcox.results)),labels=realms[order.realms],cex.axis=.7)
  axis(2,at=seq(from=floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),to=ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),by=1),labels=seq(from=floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),to=ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),by=1),las=2,cex.axis=.7)
  wilcox.results<-wilcox.results[order(unlist(lapply(wilcox.results,function(x)x[3])))]
  min.y<-floor(min(unlist(wilcox.results)))
  max.y<-ceiling(max(unlist(wilcox.results)))
  if(min.y>0){
    min.y<-0
  }
  if(max.y<0){
    max.y<-0
  }
  bxp(list(stats=matrix(unlist(wilcox.results),5,6),n=rep(10,length(wilcox.results))),xaxt='n',main=paste('difference Hot-NonHot ',variable,sep=''),ylab='diff in means of residuals',boxwex=.8,xlim=c(0,7),ylim=c(min.y,max.y),las=1,boxlwd=0.25,medlwd=1,staplelwd=0.25)
  axis(1,at=c(1:length(wilcox.results)),labels=realms[order.realms],cex.axis=.7)
  abline(h=0,lty=2)
}

plot_propdifferencesmeans_plus_vioplots_troporder<-function(table.object,variable){
  realms<-c('Afro','Austral','Indo','Nearctic','Neotrop','Palearctic')
  wilcox.results<-list()
  for(i in 1:length(table.object)){
    table.variable.realm<-table.object[[i]][[variable]]
    wilcox<-wilcox.test(table.variable.realm[table.variable.realm$hotspot==1,'value'],table.variable.realm[table.variable.realm$hotspot==0,'value'],conf.int = T)
    wilcox.results[[i]]<-c(wilcox$conf.int[1],wilcox$conf.int[1],wilcox$estimate,wilcox$conf.int[2],wilcox$conf.int[2])
  }
  
  order.realms<-c(1,2,3,5,4,6)
  plot(1,1,ylim=c(floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value))))),xlim=c(0,7),type='n',ylab='',las=1,xlab='',xaxt='n',yaxt='n',pch=16,lwd=0.5,main=variable)
  for(i in 1:length(order.realms)){
    table.variable.realm<-table.object[[order.realms[i]]][[variable]]
    vioplot(table.variable.realm[table.variable.realm$hotspot==1,'value'],col=adjustcolor( "red", alpha.f = 0.2),border=adjustcolor( "red", alpha.f = 0.2),at=i,add=T,rectCol = adjustcolor( "red", alpha.f = 0.5),lwd=0.001,colMed = adjustcolor( "red", alpha.f = 0.9),pchMed=19)
    vioplot(table.variable.realm[table.variable.realm$hotspot==0,'value'],col=adjustcolor( "blue", alpha.f = 0.2),border=adjustcolor( "blue", alpha.f = 0.2),at=i,add=T,rectCol = adjustcolor( "blue", alpha.f = 0.5),lwd=0.001,colMed = adjustcolor( "blue", alpha.f = 0.9),pchMed=19)
  }
  axis(1,at=c(1:length(wilcox.results)),labels=realms[order.realms],cex.axis=.7)
  axis(2,at=seq(from=floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),to=ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),by=1),labels=seq(from=floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),to=ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),by=1),las=2,cex.axis=.7)
  wilcox.results<-wilcox.results[order.realms]
  min.y<-floor(min(unlist(wilcox.results)))
  max.y<-ceiling(max(unlist(wilcox.results)))
  if(min.y>0){
    min.y<-0
  }
  if(max.y<0){
    max.y<-0
  }
  bxp(list(stats=matrix(unlist(wilcox.results),5,6),n=rep(10,length(wilcox.results))),xaxt='n',main=paste('difference Hot-NonHot ',variable,sep=''),ylab='diff in means of residuals',boxwex=.8,xlim=c(0,7),ylim=c(min.y,max.y),las=1,boxlwd=0.25,medlwd=1,staplelwd=0.25)
  axis(1,at=c(1:length(wilcox.results)),labels=realms[order.realms],cex.axis=.7)
  abline(h=0,lty=2)
}
plot_propdifferencesmeans_plus_vioplots_alphaorder<-function(table.object,variable){
  realms<-c('Afro','Austral','Indo','Nearctic','Neotrop','Palearctic')
  wilcox.results<-list()
  for(i in 1:length(table.object)){
    if(is.null(table.object[[i]])==F){
      table.variable.realm<-table.object[[i]][[variable]]
      wilcox<-wilcox.test(table.variable.realm[table.variable.realm$hotspot==1,'value'],table.variable.realm[table.variable.realm$hotspot==0,'value'],conf.int = T)
      wilcox.results[[i]]<-c(wilcox$conf.int[1],wilcox$conf.int[1],wilcox$estimate,wilcox$conf.int[2],wilcox$conf.int[2])  
    }
    
  }
  
  order.realms<-c(1,2,3,4,5,6)
  plot(1,1,ylim=c(floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value))))),xlim=c(0,7),type='n',ylab='',las=1,xlab='',xaxt='n',yaxt='n',pch=16,lwd=0.5,main=variable)
  for(i in 1:length(order.realms)){
    if(is.null(table.object[[i]])==F){
      table.variable.realm<-table.object[[order.realms[i]]][[variable]]
      vioplot(table.variable.realm[table.variable.realm$hotspot==1,'value'],col=adjustcolor( "red", alpha.f = 0.2),border=adjustcolor( "red", alpha.f = 0.2),at=i,add=T,rectCol = adjustcolor( "red", alpha.f = 0.5),lwd=0.001,colMed = adjustcolor( "red", alpha.f = 0.9),pchMed=19)
      vioplot(table.variable.realm[table.variable.realm$hotspot==0,'value'],col=adjustcolor( "blue", alpha.f = 0.2),border=adjustcolor( "blue", alpha.f = 0.2),at=i,add=T,rectCol = adjustcolor( "blue", alpha.f = 0.5),lwd=0.001,colMed = adjustcolor( "blue", alpha.f = 0.9),pchMed=19)  
    }
    
  }
  axis(1,at=c(1:length(wilcox.results)),labels=realms[order.realms],cex.axis=.7)
  axis(2,at=seq(from=floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),to=ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),by=1),labels=seq(from=floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),to=ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),by=1),las=2,cex.axis=.7)
  #wilcox.results<-wilcox.results[order(unlist(lapply(wilcox.results,function(x)x[3])))]
  min.y<-floor(min(unlist(wilcox.results)))
  max.y<-ceiling(max(unlist(wilcox.results)))
  if(min.y>0){
    min.y<-0
  }
  if(max.y<0){
    max.y<-0
  }
  bxp(list(stats=matrix(unlist(wilcox.results),5,6),n=rep(10,length(wilcox.results))),xaxt='n',main=paste('difference Hot-NonHot ',variable,sep=''),ylab='diff in means of residuals',boxwex=.8,xlim=c(0,7),ylim=c(min.y,max.y),las=1,boxlwd=0.25,medlwd=1,staplelwd=0.25)
  axis(1,at=c(1:length(wilcox.results)),labels=realms[order.realms],cex.axis=.7)
  abline(h=0,lty=2)
}

plot_propdifferencesmeans_plus_vioplots_nosarlm<-function(table.object,variable){
  realms<-c('Afro','Austral','Indo','Nearctic','Neotrop','Palearctic')
  wilcox.results<-list()
  for(i in 1:length(table.object)){
    colnames(table.object[[i]])[which(colnames(table.object[[i]])==variable)]<-'value'
    table.variable.realm<-table.object[[i]]
    
    wilcox<-wilcox.test(table.variable.realm[table.variable.realm$hotspot==1,'value'],table.variable.realm[table.variable.realm$hotspot==0,'value'],conf.int = T)
    wilcox.results[[i]]<-c(wilcox$conf.int[1],wilcox$conf.int[1],wilcox$estimate,wilcox$conf.int[2],wilcox$conf.int[2])
  }
  
  order.realms<-order(unlist(lapply(wilcox.results,function(x)x[3])))
  plot(1,1,ylim=c(floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]]$value)))),ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]]$value))))),xlim=c(0,7),type='n',ylab='',las=1,xlab='',xaxt='n',yaxt='n',pch=16,lwd=0.5,main=variable)
  for(i in 1:length(order.realms)){
    table.variable.realm<-table.object[[order.realms[i]]]
    vioplot(table.variable.realm[table.variable.realm$hotspot==1,'value'],col=adjustcolor( "red", alpha.f = 0.2),at=i,add=T,rectCol = adjustcolor( "red", alpha.f = 0.5),lwd=0.001,colMed = adjustcolor( "red", alpha.f = 0.9),pchMed=19)
    vioplot(table.variable.realm[table.variable.realm$hotspot==0,'value'],col=adjustcolor( "blue", alpha.f = 0.2),at=i,add=T,rectCol = adjustcolor( "blue", alpha.f = 0.5),lwd=0.001,colMed = adjustcolor( "blue", alpha.f = 0.9),pchMed=19)
  }
  axis(1,at=c(1:length(wilcox.results)),labels=realms[order.realms],cex.axis=.7)
  axis(2,at=seq(from=floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]]$value)))),to=ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]]$value)))),by=1),labels=seq(from=floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]]$value)))),to=ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]]$value)))),by=1),las=2,cex.axis=.7)
  wilcox.results<-wilcox.results[order(unlist(lapply(wilcox.results,function(x)x[3])))]
  min.y<-floor(min(unlist(wilcox.results)))
  max.y<-ceiling(max(unlist(wilcox.results)))
  if(min.y>0){
    min.y<-0
  }
  if(max.y<0){
    max.y<-0
  }
  bxp(list(stats=matrix(unlist(wilcox.results),5,6),n=rep(10,length(wilcox.results))),xaxt='n',main=paste('difference Hot-NonHot ',variable,sep=''),ylab='diff in means of residuals',boxwex=.8,xlim=c(0,7),ylim=c(min.y,max.y),las=1)
  axis(1,at=c(1:length(wilcox.results)),labels=realms[order.realms],cex.axis=.7)
  abline(h=0,lty=2)
}

plot_propdifferencesmeans_plus_vioplots_nosarlm_alphaorder<-function(table.object,variable){
  realms<-c('Afro','Austral','Indo','Nearctic','Neotrop','Palearctic')
  wilcox.results<-list()
  for(i in 1:length(table.object)){
    colnames(table.object[[i]])[which(colnames(table.object[[i]])==variable)]<-'value'
    table.variable.realm<-table.object[[i]]
    
    wilcox<-wilcox.test(table.variable.realm[table.variable.realm$hotspot==1,'value'],table.variable.realm[table.variable.realm$hotspot==0,'value'],conf.int = T)
    wilcox.results[[i]]<-c(wilcox$conf.int[1],wilcox$conf.int[1],wilcox$estimate,wilcox$conf.int[2],wilcox$conf.int[2])
  }
  
  #order.realms<-order(unlist(lapply(wilcox.results,function(x)x[3])))
  order.realms<-c(1,2,3,4,5,6)
  plot(1,1,ylim=c(floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]]$value)))),ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]]$value))))),xlim=c(0,7),type='n',ylab='',las=1,xlab='',xaxt='n',yaxt='n',pch=16,lwd=0.5,main=variable)
  for(i in 1:length(order.realms)){
    table.variable.realm<-table.object[[order.realms[i]]]
    vioplot(table.variable.realm[table.variable.realm$hotspot==1,'value'],col=adjustcolor( "red", alpha.f = 0.2),at=i,add=T,rectCol = adjustcolor( "red", alpha.f = 0.5),lwd=0.001,colMed = adjustcolor( "red", alpha.f = 0.9),pchMed=19)
    vioplot(table.variable.realm[table.variable.realm$hotspot==0,'value'],col=adjustcolor( "blue", alpha.f = 0.2),at=i,add=T,rectCol = adjustcolor( "blue", alpha.f = 0.5),lwd=0.001,colMed = adjustcolor( "blue", alpha.f = 0.9),pchMed=19)
  }
  axis(1,at=c(1:length(wilcox.results)),labels=realms[order.realms],cex.axis=.7)
  axis(2,at=seq(from=floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]]$value)))),to=ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]]$value)))),by=1),labels=seq(from=floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]]$value)))),to=ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]]$value)))),by=1),las=2,cex.axis=.7)
  #wilcox.results<-wilcox.results[order(unlist(lapply(wilcox.results,function(x)x[3])))]
  min.y<-floor(min(unlist(wilcox.results)))
  max.y<-ceiling(max(unlist(wilcox.results)))
  if(min.y>0){
    min.y<-0
  }
  if(max.y<0){
    max.y<-0
  }
  bxp(list(stats=matrix(unlist(wilcox.results),5,6),n=rep(10,length(wilcox.results))),xaxt='n',main=paste('difference Hot-NonHot ',variable,sep=''),ylab='diff in means of residuals',boxwex=.8,xlim=c(0,7),ylim=c(min.y,max.y),las=1)
  axis(1,at=c(1:length(wilcox.results)),labels=realms[order.realms],cex.axis=.7)
  abline(h=0,lty=2)
}

plot_propdifferencesmeans_plus_vioplots_vectororders<-function(table.object,variable,order.vector){
  realms<-c('Afrotropical','Australasian','Indo-Malay','Nearctic','Neotropical','Palearctic')
  wilcox.results<-list()
  for(i in 1:length(table.object)){
    table.variable.realm<-table.object[[i]][[variable]]
    wilcox<-wilcox.test(table.variable.realm[table.variable.realm$hotspot==1,'value'],table.variable.realm[table.variable.realm$hotspot==0,'value'],conf.int = T)
    wilcox.results[[i]]<-c(wilcox$conf.int[1],wilcox$conf.int[1],wilcox$estimate,wilcox$conf.int[2],wilcox$conf.int[2])
  }
  
  order.realms<-match(order.vector,realms)
  plot(1,1,ylim=c(floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value))))),xlim=c(0,7),type='n',ylab='',las=1,xlab='',xaxt='n',yaxt='n',pch=16,lwd=0.5,main=variable)
  for(i in 1:length(order.realms)){
    table.variable.realm<-table.object[[order.realms[i]]][[variable]]
    vioplot(table.variable.realm[table.variable.realm$hotspot==1,'value'],col=adjustcolor( "red", alpha.f = 0.2),at=i,add=T,rectCol = adjustcolor( "red", alpha.f = 0.5),lwd=0.001,colMed = adjustcolor( "red", alpha.f = 0.9),pchMed=19)
    vioplot(table.variable.realm[table.variable.realm$hotspot==0,'value'],col=adjustcolor( "blue", alpha.f = 0.2),at=i,add=T,rectCol = adjustcolor( "blue", alpha.f = 0.5),lwd=0.001,colMed = adjustcolor( "blue", alpha.f = 0.9),pchMed=19)
  }
  axis(1,at=c(1:length(wilcox.results)),labels=realms[order.realms],cex.axis=.7)
  axis(2,at=seq(from=floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),to=ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),by=1),labels=seq(from=floor(min(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),to=ceiling(max(unlist(lapply(c(1:length(table.object)),function(x)table.object[[x]][[variable]]$value)))),by=1),las=2,cex.axis=.7)
  wilcox.results<-wilcox.results[order.realms]
  min.y<-floor(min(unlist(wilcox.results)))
  max.y<-ceiling(max(unlist(wilcox.results)))
  if(min.y>0){
    min.y<-0
  }
  if(max.y<0){
    max.y<-0
  }
  bxp(list(stats=matrix(unlist(wilcox.results),5,6),n=rep(10,length(wilcox.results))),xaxt='n',main=paste('difference Hot-NonHot ',variable,sep=''),ylab='diff in means of residuals',boxwex=.8,xlim=c(0,7),ylim=c(min.y,max.y),las=1)
  axis(1,at=c(1:length(wilcox.results)),labels=realms[order.realms],cex.axis=.7)
  abline(h=0,lty=2)
}

